### ISSUE TITLE
I can not import the export.ndjson.

### ISSUE THREAD

**Issue by lyqwaterway** [jfrog/log-analytics#36]
Sorry, there was an error
The file could not be processed.

How to import all the object in Kibana

**Comment by lyqwaterway** [comment]
The error as below
Debug: internal, implementation, error
    SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at str (/usr/share/kibana/src/legacy/server/saved_objects/import/collect_saved_objects.js:39:19)
    at Transform.transform [as _transform] (/usr/share/kibana/src/legacy/utils/streams/map_stream.js:35:26)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Transform.Writable.write (_stream_writable.js:294:11)
    at Transform.ondata (_stream_readable.js:667:20)
    at Transform.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Transform.Readable.push (_stream_readable.js:220:10)
    at Transform.push (_stream_transform.js:151:32)
    at Transform.transform [as _transform] (/usr/share/kibana/src/legacy/utils/streams/split_stream.js:62:16)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Transform.Writable.write (_stream_writable.js:294:11)
    at module.exports.internals.Payload.ondata (_stream_readable.js:667:20)
    at module.exports.internals.Payload.emit (events.js:189:13)

**Comment by lyqwaterway** [comment]
The file i upload was wrong...
